Put connection=local into inventory for cleaner commands, als use python3 for ansible

diff --git a/.github/workflows/ansible_test.yml b/.github/workflows/ansible_test.yml
--- a/.github/workflows/ansible_test.yml
+++ b/.github/workflows/ansible_test.yml
@@ -28,13 +28,13 @@ jobs:
       run: printf '[defaults]\nroles_path=../' > ansible.cfg
 
     - name: Basic Ansible role syntax check
-      run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check
+      run: ansible-playbook -i tests/inventory --syntax-check tests/test.yml
 
     - name: Real Ansible run
-      run: ansible-playbook tests/test.yml -i tests/inventory --connection=local || echo "Done"
+      run: ansible-playbook -i tests/inventory tests/test.yml
 
     - name: Second run to check for indempotence (allowing 3 changes)
-      run: "ansible-playbook tests/test.yml -i tests/inventory --connection=local | grep -q 'changed=3.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
+      run: "ansible-playbook -i tests/inventory tests/test.yml | grep -q 'changed=3.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
 
     - name: Setup serverspec (install gem)
       run: sudo gem install serverspec
